### ISSUE TITLE
CheckApp HMI - Popups are nearly invisible

### ISSUE THREAD

**Issue by DocHardinger** [HombergerRobotics/Homberger-Hub#12]
If you use popups on the HMI and have a lot of stuff on the HMI the popups are to small or not highlighted.
So its hard for the user to see that there is a popup.

Maybe an underlaying color box would help to highlight popups. Or set hmi to loading mode automatically if there is a popup.

**Comment by HombergerRobotics** [comment]
Improvement relasesed in DRL studio version 1.8.4.
