### ISSUE TITLE
OnRobot VGP20 get_grasp_status() blocks execution

### ISSUE THREAD

**Issue by DocHardinger** [HombergerRobotics/Homberger-Hub#14]
Getting back the grasp status ( get_grasp_status() ) blocks program execution for too long time on the OnRobot VGP20. 
Its not handy if you want to use your function to check periodically the gripper status, for example in background task. Maybe its better if you can get the status without waiting. Maybe thats also true on other OnRobot functions.

For example:

get_grasp_status(no_blocking = True)

**Comment by HombergerRobotics** [comment]
All getters functions must be blocking otherwise it will be impossible to fatch resulting data.
To implement that in a no blocking way a thread + [Future/Promise](https://en.wikipedia.org/wiki/Futures_and_promises) can be used.
